baseURL: https://louisdo2108.github.io/
languageCode: en-us
title: LD'Blog
theme: "PaperMod"

languages:
    en:
        languageName: "English"
        weight: 1
        contentDir: content/en
        homeInfoParams:
          Title: "LouisDo's Blog"
          Content: >
              This is Louis Do. I am interested in Medical Image Computing and sometimes I note things down.
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Posts
                  url: "/en/"
                  weight: 1
                - name: Search
                  url: "/en/search/"
                  weight: 2
                - name: Tags
                  url: "/en/tags/"
                  weight: 3
                - name: FAQ
                  url: "/en/faq/"
                  weight: 4
                - name: Archive
                  url: "/archives/"
                  weight: 5
    zh-tw:
        languageName: "中文"
        weight: 2
        contentDir: content/zh-tw
        homeInfoParams:
          Title: "杜俊力 Blog"
          Content: >
              大家好，我是杜俊力。我對醫學影像計算感興趣。我經常記錄下我所學到的知識。
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: 網誌
                  url: "/"
                  weight: 1
                - name: 搜索
                  url: "/search/"
                  weight: 2
                - name: Tags
                  url: "/tags/"
                  weight: 3
                - name: FAQ
                  url: "/faq/"
                  weight: 4
                - name: 檔案
                  url: "/archives/"
                  weight: 5
    yue:
        languageName: "粵語"
        weight: 3
        contentDir: content/yue
        homeInfoParams:
          Title: "杜俊力 Blog"
          Content: >
              大家好，我係杜俊力。我鍾意研究醫學影像計算。耐唔中我會抄底我學到啲嘢。
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: 網誌
                  url: "/"
                  weight: 1
                - name: 搜索
                  url: "/search/"
                  weight: 2
                - name: Tags
                  url: "/tags/"
                  weight: 3
                - name: FAQ
                  url: "/faq/"
                  weight: 4
                - name: 檔案
                  url: "/archives/"
                  weight: 5
    vi:
        languageName: "Tiếng Việt"
        weight: 4
        contentDir: content/vi
        homeInfoParams:
          Title: "Blog của Louis Do"
          Content: >
              Chào mọi người, mình là Lực. Mình đang nghiên cứu về xử lý ảnh y học và mình hay ghi chép lại những gì mình học và đọc được.
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Bài Viết
                  url: "/"
                  weight: 1
                - name: Tìm Kiếm
                  url: "/search/"
                  weight: 2
                - name: Tags
                  url: "/tags/"
                  weight: 3
                - name: FAQ
                  url: "/faq/"
                  weight: 4
                - name: Lưu trữ
                  url: "/archives/"
                  weight: 5
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "LouisDo"
    author: LouisDo2108
    # author: ["Me", "You"] # multiple authors

    defaultTheme: dark #auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: true
    # comments: false
    # images: ["papermod-cover.png"]

    # profileMode:
    #     enabled: false
    #     title: LouisDo2108
    #     imageUrl: "#"
    #     imageTitle: my image
    #     # imageWidth: 120
    #     # imageHeight: 120
    #     buttons:
    #         - name: Archives
    #           url: archives
    #         - name: Tags
    #           url: tags

    # homeInfoParams:
    #     Title: "LouisDo2108's Blog"
    #     Content: >
    #         This is Louis Do. I am interested in Medical Imaging and sometimes I note things down.
    socialIcons:
        - name: github
          url: "https://github.com/LouisDo2108"
        - name: linkedin
          url: "https://www.linkedin.com/in/htluc2001/"
        - name: googlescholar
          url: "https://scholar.google.com/citations?user=QFkhDJcAAAAJ&hl=en"
        - name: soundcloud
          url: "https://soundcloud.com/user-759044871"
        - name: twitter
          url: "https://twitter.com/LouisAckerman74"

    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        responsiveImages: false
        linkFullImages: true
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true